name: Linter

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, dom, fileinfo, curl, tokenizer, bcmath
          ini-values: memory_limit=-1
          coverage: none

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # Install PHP dependencies
      - name: Install Composer dependencies
        run: |
          composer install --no-ansi --no-interaction --no-progress --prefer-dist

      # Install Node dependencies
      - name: Install NPM dependencies
        run: npm ci

      # PHP Linting
      - name: Run PHP Syntax Check
        run: find . -type f -name '*.php' -not -path './vendor/*' -exec php -l {} \;

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test

      # JavaScript/TypeScript Linting
      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript Check (if using TS)
        if: contains(fromJson('package.json').devDependencies, 'typescript')
        run: npm run type-check

      # Vue.js Specific Linting
      - name: Run Vue Template Linter
        run: npm run lint:vue

      # Formatting Checks
      - name: Check PHP Code Style
        run: ./vendor/bin/pint --dry-run

      - name: Check JavaScript Formatting
        run: npm run format:check

      # Optional: Auto-fix and commit (uncomment if needed)
      # - name: Fix and commit changes
      #   if: always() && github.ref == 'refs/heads/main'
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: 'style: auto-fix linting issues'
      #     file_pattern: '*.php *.js *.vue *.ts'